// vue-job-portal/src/components/HomeCards.vue
<script setup>
import Card from '@/components/Card.vue'
import { RouterLink } from 'vue-router'
</script>

<template>
  <section class="py-4">
    <div class="container-xl lg:container m-auto">
      <div class="grid grid-cols-1 md:grid-cols-2 gap-4 p-4 rounded-lg">
        <Card>
          <h2 class="text-2xl font-bold">For Developers</h2>
          <p class="mt-2 mb-4">Browse our Vue jobs and start your career today</p>
          <RouterLink
            to="jobs"
            class="inline-block bg-black text-white rounded-lg px-4 py-2 hover:bg-gray-700"
          >
            Browse Jobs
          </RouterLink>
        </Card>
        <Card bg="bg-green-100">
          <h2 class="text-2xl font-bold">For Employers</h2>
          <p class="mt-2 mb-4">List your job to find the perfect developer for the role</p>
          <RouterLink
            to="/jobs/add"
            class="inline-block bg-green-500 text-white rounded-lg px-4 py-2 hover:bg-green-600"
          >
            Add Job
          </RouterLink>
        </Card>
      </div>
    </div>
  </section>
</template>

// react-job-portal/src/components/HomeCards.jsx
import Card from "./Card.jsx";
import {Link} from "react-router-dom";
const HomeCards = () => {
    return (
        <section className="py-4">
            <div className="container-xl lg:container m-auto">
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4 p-4 rounded-lg">
                    <Card>
                            <h2 className="text-2xl font-bold">For Developers</h2>
                            <p className="mt-2 mb-4">
                                Browse our React jobs and start your career today
                            </p>
                            <Link
                                to="/jobs"
                                className="inline-block bg-black text-white rounded-lg px-4 py-2 hover:bg-gray-700"
                            >
                                Browse Jobs
                            </Link>
                        </Card>
                    <Card bg='bg-indigo-100 '>
                        <h2 className="text-2xl font-bold">For Employers</h2>
                        <p className="mt-2 mb-4">
                            List your job to find the perfect developer for the role
                        </p>
                        <Link
                            to="/add-job"
                            className="inline-block bg-indigo-500 text-white rounded-lg px-4 py-2 hover:bg-indigo-600"
                        >
                            Add Job
                        </Link>
                    </Card>
                </div>
            </div>
        </section>
    )
}

export default HomeCards
