// react-job-portal/src/components/JobListings.jsx
import JobListing from "./JobListing.jsx";
import {useState, useEffect} from "react";
import Spinner from "../components/Spinner";

const JobListings = ({isHome = false}) => {
const [jobs, setJobs] = useState([]);
const [loading, setLoading] = useState(true);
    useEffect( () => {
        const fetchJobs = async () => {
            const apiUrl = isHome ? "/api/jobs?_limit=3" : "/api/jobs";
            try {
                const response = await fetch(apiUrl);
                const data = await response.json();
                setJobs(data);
            } catch (error) {
                console.log('Error fetching data', error);
            } finally {
                setLoading(false);
            }
        }
        fetchJobs();
    }, []); //array is a variable that will be watched mostly is empty
return (
        <section className="bg-blue-50 px-4 py-10">
            <div className="container-xl lg:container m-auto">
                <h2 className="text-3xl font-bold text-indigo-500 mb-6 text-center">
                    { isHome ? 'RecentJobs' : 'Browse Jobs'}
                </h2>
                    { loading ?
                        <Spinner loading={loading}/> :
                        <>
                        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">

                        {jobs.map((job) => (
                            <JobListing key={job.id} job={job} />
                            ))}
                        </div>
                        </>
                   }
            </div>
        </section>
    )
}

export default JobListings;

// vue-job-portal/src/components/JobListings.vue
<script setup>
import {ref, reactive, defineProps, onMounted} from 'vue';
import JobListing from '@/components/JobListing.vue'
import { RouterLink } from 'vue-router';
import axios from 'axios';
import PulseLoader from "vue-spinner/src/PulseLoader.vue"

const jobs = ref([]);
const state = reactive({
  jobs: [],
  isLoading: true,
})
defineProps({
  limit: {
    type: Number,
  },
  showButton: {
    type: Boolean,
    default: false
  }
})

onMounted(async () => {
  try{
    const response = await axios.get('api/jobs');
    state.jobs = response.data;
  } catch (error){
    console.log("ERROR fetching data");
  } finally {
    state.isLoading = false;
  }
})

</script>

<template>
  <section class="bg-blue-50 px-4 py-10">
    <div class="container-xl lg:container m-auto">
      <h2 class="text-3xl font-bold text-green-500 mb-6 text-center">
        Browse Jobs
      </h2>
      <!-- SHow loading spinner while loading is true -->
      <div v-if="state.isLoading" class="text-center text-gray-600 pz-6">
        <PulseLoader/>
      </div>
      <!-- SHow job listing when done loading -->
      <div class="grid grid-cols-1 md:grid-cols-3 gap-6" v-else>
          <JobListing  v-for="job in state.jobs.slice(0, limit || state.jobs.length)" :key="job.id" :job="job" />
      </div>
    </div>
  </section>

  <section class="m-auto max-w-lg my-10 px-6" v-if="showButton">
    <RouterLink
      to="/jobs"
      class="block bg-black text-white text-center py-4 px-6 rounded-xl hover:bg-gray-700"
    >View All Jobs</RouterLink
    >
  </section>

</template>
